/* mix3config_pre.h.  Generated by configure.  */
/* mix3config_pre.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define MIX3_HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define MIX3_HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define MIX3_HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define MIX3_HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define MIX3_HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define MIX3_HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define MIX3_HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define MIX3_HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define MIX3_HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define MIX3_HAVE_UNISTD_H 1

/* Name of package */
#define MIX3_PACKAGE "cminion"

/* Define to the address where bug reports for this package should be sent. */
#define MIX3_PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define MIX3_PACKAGE_NAME "cminion"

/* Define to the full name and version of this package. */
#define MIX3_PACKAGE_STRING "cminion 0.1"

/* Define to the one symbol short name of this package. */
#define MIX3_PACKAGE_TARNAME "cminion"

/* Define to the version of this package. */
#define MIX3_PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define MIX3_STDC_HEADERS 1

/* Version number of package */
#define MIX3_VERSION "0.1"
